targets:
  - name: kube-dns
    host: kube-dns.kube-system.svc.cluster.local
    ports: [53]
    http:
      enabled: false
      url: ""
      method: GET
    tls:
      enabled: false
      server_name: ""
  - name: kubernetes-api
    host: kubernetes.default.svc.cluster.local
    ports: [443]
    http:
      enabled: true
      url: https://kubernetes.default.svc.cluster.local/healthz
      method: GET
    tls:
      enabled: true
      server_name: kubernetes.default.svc
