targets:
  - name: placeholder_prod
    host: service.prod.company.local
    path: /
    port: 443
    protocol: https
    curl:
      insecure: true
      verbose: true
      follow_redirects: true
    timeout: 10
    retries: 2
    tags:
      - smoke
    checks:
      - dns
      - tcp
      - http
      - tls
